version: '3.7'

services:
  db:
    image: postgres:14.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
  web:
    build: 
      context: .
    command: > 
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn store.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/code

volumes:
  postgres_data:
